AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket with environment tagging'

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: pr-test-stack-test-bucket
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: GithubActionsTesting

  Outputs:
    BucketName:
      Value: !Ref MyS3Bucket
      Description: 'Name of the created S3 bucket'
      
